routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('menu.create');
});
// MENU
Route::resource('menu', MenuController::class);

// SHOP
Route::resource('shop', ShopController::class);

// Item
Route::resource('item', ItemController::class);

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'cover', 'image', 'price', 'menu_id', 'shop_id'];

    public function menu(){
        return $this->belongsTo(Menu::class);
    }
    public function shop(){
        return $this->belongsTo(Shop::class);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Item;
use App\Models\Menu;
use App\Models\Shop;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $itemData= Item::all();
        return view('item.index', compact('itemData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $menus = Menu::all();
        $shops = Shop::all();
        return view('item.create')->with([
            'menus' => $menus,
            'shops' => $shops
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!$request->name){
            return redirect()->route('item.create')->with('error', 'Please Enter Item Name');
        }
        else if(!$request->price){
            return redirect()->route('item.create')->with('error', 'Please Enter Item Price');
        }
        else if(!$request->menu_id){
            return redirect()->route('item.create')->with('error', 'Please Select Menu');
        }
        else if(!$request->shop_id){
            return redirect()->route('item.create')->with('error', 'Please Select Shop');
        }
        else if(!$request->file('cover')){
            return redirect()->route('item.create')->with('error', 'Please Choose Cover Image');
        }
        else if(!$request->file('images')){
            return redirect()->route('item.create')->with('error', 'Please Choose Images');
        }
        else{
            $data= new Item();

            if($request->file('cover')){
                $file= $request->file('cover');
                $path = "storage/images/item/";
                $filename= date('YmdHi').$file->getClientOriginalName();
                $file-> storeAs('public/images/item/', $filename);
                $data['cover'] = $path.$filename;
            }
            if($request->file('images')){
                $files= $request->file('images');
                foreach($files as $file){
                    $filename= date('YmdHi').$file->getClientOriginalName();
                    $path = "storage/images/item/";
                    $file-> storeAs('public/images/item/', $filename);
                    $imgs[] = $path.$filename;
                }
                $imgstr = implode(", ", $imgs);
                $data['image'] = $imgstr;
            }
            $data['name'] = $request->name;
            $data['price'] = $request->price;
            $data['menu_id'] = $request->menu_id;
            $data['shop_id'] = $request->shop_id;
            $data->save();
            return redirect()->route('item.index')->with('success', 'Add Item successfully.');
        }
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $menus = Menu::all();
        $shops = Shop::all();
        return view('item.edit')->with([
            'item'=>$item,
            'menus' => $menus,
            'shops' => $shops
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        if($request->file('cover')){
            $file= $request->file('cover');
            $path = "storage/images/item/";
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file-> storeAs('public/images/item/', $filename);

            if(file_exists($item->cover)){
                unlink($item->cover);
            }

            $item->cover = $path.$filename;
        }
        if($request->file('images')){
            $files= $request->file('images');
            foreach($files as $file){
                $filename= date('YmdHi').$file->getClientOriginalName();
                $path = "storage/images/item/";
                $file-> storeAs('public/images/item/', $filename);
                $imgs[] = $path.$filename;
            }
            // dd($item->image);
            $oldimgs = explode(", ", $item->image);
            foreach ($oldimgs as $oldimg){
                if(file_exists($oldimg)){
                    unlink($oldimg);
                }
            }

            $imgstr = implode(", ", $imgs);
            $item->image = $imgstr;
        }
        $item->name = $request->name;
        $item->price = $request->price;
        $item->menu_id = $request->menu_id;
        $item->shop_id = $request->shop_id;
        $item->save();
        return redirect()->route('item.index')->with('success','Item updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        return redirect()->route('item.index')->with('success', 'Delete Item successfully.');
    }
}

resources/views/item/create.blade.php
@extends('layout')

@section('title', 'Add Item')

@section('style', '3')

@section("content")
<div class="container w-50"><br><br><br>

@include('common.alert')

  <h2><i class="fa-solid fa-plus"></i> Add New Item</h2>
  <hr>
  <form method="post" action="{{ route('item.store') }}" enctype="multipart/form-data">
    @csrf
    <div>
      <label><h4>Enter Name *</h4></label>
      <input type="text" class="form-control" name="name">
    </div>
    <br>
    <div>
      <label><h4>Add Cover *</h4></label>
      <input type="file" class="form-control" name="cover">
    </div><br>
    <div>
      <label><h4>Add Image *</h4></label>
      <input type="file" class="form-control" name="images[]" multiple>
    </div><br>
    <div>
    </div>
    <div>
      <label><h4>Price *</h4></label>
      <input type="number" class="form-control" name="price">
    </div><br>
    <div>
      <label><h4>Menu *</h4></label>
      <select name="menu_id" class="form-control">
        <option value=" " disabled selected>--Select Menu--</option>
      @foreach($menus as $menu)
        <option value="{{$menu->id}}" >{{$menu->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>
    <div>
      <label><h4>Shop *</h4></label>
      <select name="shop_id" class="form-control">
        <option value=" " disabled selected>--Select Shop--</option>
      @foreach($shops as $shop)
        <option value="{{$shop->id}}" >{{$shop->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>
    <br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Add Item</button>
    </div>
  </form>
</div>
@endsection

resources/views/item/edit.blade.php
@extends('layout')

@section('title', 'Edit Item')

@section('style', '3')

@section("content")
<div class="container w-50"><br><br><br>
  <h2><i class="fa-solid fa-pen-to-square"></i> Edit Item</h2>
  <hr>
  <form method="post" action="{{route('item.update', ['item' => $item->id])}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div>
      <label><h4>Name</h4></label>
      <input type="text" class="form-control" name="name" value="{{$item->name}}">
    </div>
    <br>
    <div>
      <label><h4>Old Cover</h4></label><br>
      <img src="{{ asset($item->cover) }}" alt="old image" style="width:200px" class="rounded shadow image" onclick="showImage(this.src)">
    </div><br>
    <div>
      <label><h4>New Cover</h4></label>
      <input type="file" class="form-control" name="cover">
    </div><br>
    <div>
      <label><h4>Old Images</h4></label><br>
      @foreach(explode(', ', $item->image) as $path)
            <img src="{{ asset($path) }}" style="width: 100px;" class="rounded shadow image" onclick="showImage(this.src)">
          @endforeach
    </div><br>
    <div>
      <label><h4>New Images</h4></label>
      <input type="file" class="form-control" name="images[]" multiple>
    </div><br>
    <div>
    </div>
    <div>
      <label><h4>Price</h4></label>
      <input type="text" class="form-control" name="price" value="{{$item->price}}">
    </div><br>
    <div>
      <label><h4>Menu</h4></label>
      <select name="menu_id" class="form-control">
      @foreach($menus as $menu)
        <option value="{{$menu->id}}"  @if($menu->id == $item->menu_id) selected="selected" @endif > {{$menu->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>
    <div>
      <label><h4>Shop</h4></label>
      <select name="shop_id" class="form-control">
      @foreach($shops as $shop)
        <option value="{{$shop->id}}" @if($shop->id == $item->shop_id) selected="selected" @endif > {{$shop->name ?? ''}}</option>
        @endforeach
      </select> 
    </div><br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Edit Item</button>
    </div>
  </form>
</div>
@endsection

resources/views/item/index.blade.php
@extends('layout')

@section('title', 'Item List')

@section('style', '3')

@section("content")
<div class="container"><br><br><br>
@include('common.alert')
<h3 class="float-start">Item List</h3>
    <a href="{{route('item.create')}}" class="btn btn-success px-5 mx-3 float-end"><i class="fa-regular fa-plus"></i> ADD NEW SHOP</a>
    <br><br><hr>
    <table class="table table-striped m-3 p-5">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Cover</th>
          <th scope="col">Image</th>
          <th scope="col">Price</th>
          <th scope="col">Menu</th>
          <th scope="col">Shop</th>
        </tr>
      </thead>
        @foreach($itemData as $data)
        <tr>
          <td>{{$data->id}}</td>
          <td>{{$data->name}}</td>
          <td>
	          <img src="{{ asset($data->cover) }}"style="width: 200px;" class="rounded shadow">
	        </td>
          
          <td style="width: 300px">
          @foreach(explode(', ', $data->image) as $path)
            <img src="{{ asset($path) }}" style="width: 100px;" class="rounded shadow">
          @endforeach
          </td>
          
          <td>{{$data->price}}</td>
          <td>{{$data->menu->name ?? 'unknown'}}</td>
          <td>{{$data->shop->name ?? 'unknown'}}</td>
          <td><a href="{{ route('item.edit',$data->id) }}" class="btn btn-outline-primary"><i class="fa-solid fa-pen-to-square"></i> Edit</a></td>
          <td>
              <form action="{{ route('item.destroy', $data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-outline-danger"  onclick="return confirm('Are you sure to DELETE?')"><i class="fa-solid fa-trash-can"></i> Delete</button>
              </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
@endsection

resources/views/item/index_new.blade.php
@extends('layout')

@section('title', 'Item List')

@section('style', '3')

@section("content")
<div class="container"><br><br><br>
@include('common.alert')
<h3 class="float-start">Item List</h3>
    <a href="{{route('item.create')}}" class="btn btn-success px-5 mx-3 float-end"><i class="fa-regular fa-plus"></i> ADD NEW SHOP</a>
    <br><br><hr>
    
    <!-- Old Frame -->
        @foreach($itemData as $data)
        <tr>
          <td>{{$data->id}}</td>
          <td>{{$data->name}}</td>
          <td>
	          <img src="{{ asset($data->cover) }}"style="width: 200px;" class="rounded shadow">
	        </td>
          
          <td style="width: 300px">
          @foreach(explode(', ', $data->image) as $path)
            <img src="{{ asset($path) }}" style="width: 100px;" class="rounded shadow">
          @endforeach
          </td>
          
          <td>{{$data->price}}</td>
          <td>{{$data->menu->name ?? 'unknown'}}</td>
          <td>{{$data->shop->name ?? 'unknown'}}</td>
          <td><a href="{{ route('item.edit',$data->id) }}" class="btn btn-outline-primary"><i class="fa-solid fa-pen-to-square"></i></a></td>
          <td>
              <form action="{{ route('item.destroy', $data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-outline-danger"  onclick="return confirm('Are you sure to DELETE?')"><i class="fa-solid fa-trash-can"></i></button>
              </form>
          </td>
        </tr>
        @endforeach
@endsection