routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('menu.create');
});
// MENU
Route::resource('menu', MenuController::class);

// SHOP
Route::resource('shop', ShopController::class);

// Item
Route::resource('item', ItemController::class);

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'address', 'logo'];

    public function item(){
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Shop;

class ShopController extends Controller
{
    // /**
    //  * Display a listing of the resource.
    //  *
    //  * @return \Illuminate\Http\Response
    //  */
    public function index()
    {
        $shopData= Shop::all();
        return view('shop.index', compact('shopData'));
    }

    // /**
    //  * Show the form for creating a new resource.
    //  *
    //  * @return \Illuminate\Http\Response
    //  */
    public function create()
    {
        return view('shop.create');
    }

    // /**
    //  * Store a newly created resource in storage.
    //  *
    //  * @param  \Illuminate\Http\Request  $request
    //  * @return \Illuminate\Http\Response
    //  */
    public function store(Request $request)
    {
        if(!$request["name"]){
            return redirect()->route('shop.create')->with('error', 'Please Enter Shop Name');    
        }
        else if(!$request->file('logo')){
            return redirect()->route('shop.create')->with('error', 'Please Choose Shop Logo');    
        }
        else{
            $data= new Shop();

            if($request->file('logo')){
                $file= $request->file('logo');
                $path = "storage/images/shop/";
                $filename= date('YmdHi').$file->getClientOriginalName();
                $file-> storeAs('public/images/shop/', $filename);
                $data['logo']= $path.$filename;
            }
            $data['name'] = $request->name;
            $data['address'] = $request->address;
            $data->save();
            return redirect()->route('shop.index')->with('success', 'Add Shop successfully.');
        }
    }

    // /**
    //  * Display the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function show($id)
    {
        //
    }

    // /**
    //  * Show the form for editing the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function edit(Shop $shop)
    {
        return view('shop.edit',[
            'shop'=>$shop
        ]);
    }

    // /**
    //  * Update the specified resource in storage.
    //  *
    //  * @param  \Illuminate\Http\Request  $request
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function update(Request $request, Shop $shop)
    {
        if($request->file('logo')){
            $file= $request->file('logo');
            $path = "storage/images/shop/";
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file-> storeAs('public/images/shop/', $filename);

            if(file_exists($shop->logo)){
                unlink($shop->logo);
            }

            $shop->logo = $path.$filename;
        }
        $shop->name = $request->name;
        $shop->address = $request->address;
        $shop->save();
        return redirect()->route('shop.index')->with('success','Shop updated successfully');
    }

    // /**
    //  * Remove the specified resource from storage.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function destroy(Shop $shop)
    {
        $shop->item()->delete();
        $shop->delete();
        return redirect()->route('shop.index')->with('success', 'Delete Shop successfully.');
    }
}

resources/views/shop/create.blade.php
@extends('layout')

@section('title', 'Add Shop')

@section('style', '2')

@section("content")
<div class="container w-50"><br><br><br>

@include('common.alert')

  <h2><i class="fa-solid fa-plus"></i> Add New Shop</h2>
  <hr>
  <form method="post" action="{{ route('shop.store') }}" enctype="multipart/form-data">
    @csrf
    <div>
      <label><h4>Enter Name *</h4></label>
      <input type="text" class="form-control" name="name">
    </div><br>
    <div>
      <label><h4>Enter Address</h4></label>
      <input type="text" class="form-control" name="address">
    </div><br>
    <div>
      <label><h4>Add Logo *</h4></label>
      <input type="file" class="form-control" name="logo">
    </div>
<br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Add Shop</button>
    </div>
  </form>
</div>
@endsection

resources/views/shop/edit.blade.php
@extends('layout')

@section('title', 'Edit Shop')

@section('style', '2')

@section("content")
<div class="container w-50"><br><br><br>
  <h2><i class="fa-solid fa-pen-to-square"></i> Edit Shop</h2>
  <hr>
  <form method="post" action="{{route('shop.update', ['shop' => $shop->id])}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div>
      <label><h4>Name</h4></label>
      <input type="text" class="form-control" name="name" value="{{$shop->name}}">
    </div><br>
    <div>
      <label><h4>Address</h4></label>
      <input type="text" class="form-control" name="address" value="{{$shop->address}}">
    </div><br>
    <div>
      <label><h4>Old Logo</h4></label><br>
      <img src="{{ asset($shop->logo) }}" alt="old image" style="width:200px" class="rounded shadow image" onclick="showImage(this.src)">
    </div><br>
    <div>
      <label><h4>New Logo</h4></label>
      <input type="file" class="form-control" name="logo">
    </div>
<br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Edit Shop</button>
    </div>
  </form>
</div>
@endsection

resources/views/shop/index.blade.php
@extends('layout')

@section('title', 'Shop List')

@section('style', '2')

@section("content")
<div class="container"><br><br><br>
@include('common.alert')
    <h3 class="float-start">SHOPs</h3>
    <a href="{{route('shop.create')}}" class="btn btn-success px-5 mx-3 float-end"><i class="fa-regular fa-plus"></i> ADD NEW SHOP</a>
    <br><br><hr>
       <div class="row justify-content-center align-items-start">
          @foreach($shopData as $data)
            <div class="card col-4 m-4 position-relative py-2 image" style="width: 300px;">
              <div class="position-absolute bg-danger rounded text-light px-3 py-1">ID: {{$data->id}}</div>
              <img src="{{ asset($data->logo) }}" class="card-img-top" alt="logo">
              <div class="card-body">
                <h5 class="card-title">{{$data->name}}</h5>
                <p class="card-text">Address: {{$data->address}}</p>
                <div class="d-flex justify-content-around">
                  <a href="{{ route('shop.edit',$data->id) }}" class="btn btn-outline-primary"><i class="fa-solid fa-pen-to-square"></i> Edit</a>
                  <form action="{{ route('shop.destroy', $data->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-outline-danger"  onclick="return confirm('Are you sure to DELETE?')"><i class="fa-solid fa-trash-can"></i> Delete</button>
                    </form>
                </div>
              </div>
            </div>
            @endforeach
       </div>
  </div>
@endsection

resources/views/shop/index_bkp.blade.php
@extends('layout')

@section('title', 'Shop List')

@section('style', '2')

@section("content")
<div class="container"><br><br><br>
@include('common.alert')
    <h3>View all Shop</h3><hr>
    <a href="{{route('shop.create')}}" class="btn btn-success px-5 mx-3 float-end"><i class="fa-regular fa-plus"></i> ADD NEW SHOP</a>
    <table class="table table-striped m-3 p-5">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Address</th>
          <th scope="col">Logo</th>
        </tr>
      </thead>
      <tbody>
        @foreach($shopData as $data)
        <tr>
          <td>{{$data->id}}</td>
          <td>{{$data->name}}</td>
          <td>{{$data->address}}</td>
          <td>
            <img src="{{ asset($data->logo) }}" style="width: 200px;" class="shadow rounded">
          </td>
          <td><a href="{{ route('shop.edit',$data->id) }}" class="btn btn-outline-primary"><i class="fa-solid fa-pen-to-square"></i></a></td>
          <td>
              <form action="{{ route('shop.destroy', $data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')

                  <button type="submit" class="btn btn-outline-danger"  onclick="return confirm('Are you sure to DELETE?')"><i class="fa-solid fa-trash-can"></i></button>
              </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
@endsection