routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ItemController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('menu.create');
});
// MENU
Route::resource('menu', MenuController::class);

// SHOP
Route::resource('shop', ShopController::class);

// Item
Route::resource('item', ItemController::class);

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'cover'];

    public function item(){
        return $this->hasMany(Item::class);
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Menu;

class MenuController extends Controller
{
    // /**
    //  * Display a listing of the resource.
    //  *
    //  * @return \Illuminate\Http\Response
    //  */
    public function index()
    {
        $menuData = Menu::all();
        return view('menu.index', compact('menuData'));
    }

    // /**
    //  * Show the form for creating a new resource.
    //  *
    //  * @return \Illuminate\Http\Response
    //  */
    public function create()
    {
        return view('menu.create');
    }

    // /**
    //  * Store a newly created resource in storage.
    //  *
    //  * @param  \Illuminate\Http\Request  $request
    //  * @return \Illuminate\Http\Response
    //  */
    public function store(Request $request)
    {
        if(!$request["name"]){
            return redirect()->route('menu.create')->with('error', 'Please Enter Menu Name');    
        }
        else if(!$request->file('cover')){
            return redirect()->route('menu.create')->with('error', 'Please Choose Cover Image');    
        }
        else{
            $data= new Menu();
            if($request->file('cover')){
                $file= $request["cover"];
                $path = "storage/images/menu/";
                $filename= date('YmdHi').$file->getClientOriginalName();
                $file-> storeAs('public/images/menu/', $filename);
                $data['cover']= $path.$filename;
            }
            $data['name'] = $request->name;
            $data->save();
            return redirect()->route('menu.index')->with('success', 'Add Menu Successfully.');
        }
    }

    // /**
    //  * Display the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function show($id)
    {
        
    }

    // /**
    //  * Show the form for editing the specified resource.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function edit(Menu $menu)
    {
    
        return view('menu.edit',[
            'menu'=>$menu
        ]);
    }

    // /**
    //  * Update the specified resource in storage.
    //  *
    //  * @param  \Illuminate\Http\Request  $request
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function update(Request $request, Menu $menu)
    {
        if($request->file('cover')){
            $file= $request->file('cover');
            $path = "storage/images/menu/";
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file-> storeAs('public/images/menu/', $filename);

            if(file_exists($menu->cover)){
                unlink($menu->cover);
            }
            $menu->cover = $path.$filename;
        }
        $menu->name = $request->name;
        $menu->save();
        return redirect()->route('menu.index')->with('success','Menu updated successfully');
    }

    // /**
    //  * Remove the specified resource from storage.
    //  *
    //  * @param  int  $id
    //  * @return \Illuminate\Http\Response
    //  */
    public function destroy(Menu $menu)
    {
        // delete related   
        $menu->item()->delete();

        $menu->delete();
        return redirect()->route('menu.index')->with('success', 'Delete Menu successfully.');
    }
}

resources/views/menu/create.blade.php
@extends('layout')

@section('title', 'Add Menu')

@section('style', '1')

@section("content")
<div class="container w-50"><br><br><br>

@include('common.alert')

  <h2><i class="fa-solid fa-plus"></i> Add New Menu</h2>
  <hr>
  <form method="post" action="{{ route('menu.store') }}" enctype="multipart/form-data">
    @csrf
    <div>
      <label><h4>Enter Name *</h4></label>
      <input type="text" class="form-control" name="name">
    </div>
    <br>
    <div>
      <label><h4>Add Cover *</h4></label>
      <input type="file" class="form-control" name="cover">
    </div>
    <br><br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Add Menu</button>
    </div>
  </form>
</div>
@endsection

resources/views/menu/edit.blade.php
@extends('layout')

@section('title', 'Edit Menu')

@section('style', '1')

@section("content")
<div class="container w-50"><br><br><br>
  <h2><i class="fa-solid fa-pen-to-square"></i> Edit Menu</h2>
  <hr>
  <form method="post" action="{{route('menu.update', ['menu' => $menu->id])}}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div>
      <label><h4>Name</h4></label>
      <input type="text" class="form-control" name="name" value="{{$menu->name}}">
    </div>
    <br>
    <div>
      <label><h4>Old Cover</h4></label><br>
      <img src="{{ asset($menu->cover) }}" alt="old image"style="width: 200px;" class="image shadow rounded" onclick="showImage(this.src)">
    </div>
    <br>
    <div>
      <label><h4>New Cover</h4></label>
      <input type="file" class="form-control" name="cover">
    </div>
    <br><br>
    <div class="mb-5">
      <button type="submit" class="btn btn-success px-5">Edit Menu</button>
    </div>
  </form>
</div>
@endsection

resources/views/menu/index.blade.php
@extends('layout')

@section('title', 'Menu List')

@section('style', '1')

@section("content")
<div class="container"><br><br><br>
@include('common.alert')
<h3 class="float-start">MENUs</h3>
    <a href="{{route('menu.create')}}" class="btn btn-success px-5 mx-3 float-end"><i class="fa-regular fa-plus"></i> ADD NEW SHOP</a>
    <br><br><hr>
    <table class="table table-striped m-3 p-5">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Cover</th>
        </tr>
      </thead>
      <tbody>
        @foreach($menuData as $data)
        <tr>
          <td>{{$data->id}}</td>
          <td>{{$data->name}}</td>
          <td>
            <img src="{{ asset($data->cover) }}" class="rounded shadow" style="width: 200px;">
          </td>
          <td><a class="btn btn-outline-primary" href="{{ route('menu.edit',$data->id) }}"><i class="fa-solid fa-pen-to-square"> </i> Edit</a></td>
          <td>
              <form action="{{ route('menu.destroy',$data->id) }}" method="POST">
                  @csrf
                  @method('DELETE')

                  <button type="submit" class="btn btn-outline-danger" onclick="return confirm('Are you sure to DELETE?')"><i class="fa-solid fa-trash-can"> </i> Delete</button>
              </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
@endsection